### ISSUE TITLE
Restric td-agent logs to warn, error and critical type only

### ISSUE THREAD

**Issue by aarunkushwahaa** [fluent/fluentd-docs-gitbook#100]
I used "<match fluent.{warn,error,fatal}> @type stdout </match>"to filter the td-agent logs but it didn't work as per thought whereas < system >log_level warn " woks but i don't it for system. I want it to be specific to td-agaent. But not for all other plugins or whatever.

How can i suppress other logs and log only warn,error,fatal. 
Also, while filtering <match fluent.{warn,error,fatal}> , do I need to set <match fluent.{info,trace,debug}> to @type null?

Note: I tried above scenarios from documentation page of fluentd.

**Comment by ganmacs** [comment]
Please use google groups to ask this kind of issue. 
https://groups.google.com/forum/#!forum/fluentd
