### ISSUE TITLE
Instructions for RHEL8 or CentOS 8

### ISSUE THREAD

**Issue by vwbusguy** [fluent/fluentd-docs-gitbook#106]
The docs currently reference td-agent for RPM based systems, however td-agent does not have CentOS/RHEL 8 builds (https://github.com/treasure-data/omnibus-td-agent/issues/205), it might be helpful to point RHEL/CentOS 8 users to https://docs.fluentd.org/installation/install-by-gem for now until an RPM is available, since installation via gem works in RHEL 8.

**Comment by repeatedly** [comment]
Forgot to fix message in the commit.
https://github.com/fluent/fluentd-docs-gitbook/commit/d8450c03141629578f9a5436c879ce9e5b0d59b4 fixes this issue.

**Comment by vwbusguy** [comment]
Many thanks, @repeatedly

**Comment by vwbusguy** [comment]
As a followup, td-agent is now available for RHEL/CentOS 8 per https://github.com/treasure-data/omnibus-td-agent/issues/205 (thanks @repeatedly )
The RPM link is https://td-agent-package-browser.herokuapp.com/3/redhat/8/x86_64
