### ISSUE TITLE
GitHub links are broken

### ISSUE THREAD

**Issue by csimani** [fluent/fluentd-docs-gitbook#107]
https://docs.fluentd.org/container-deployment/install-by-docker

Links which are broken:
Docker Logging Driver and Fluentd - https://github.com/fluent/fluentd-docs-gitbook/tree/f5f5f45fd170a81e4f34226d168621bcd4eb7e48/articles/docker-logging.md
Docker Logging via EFK (Elasticsearch + Fluentd + Kibana) Stack with Docker Compose - https://github.com/fluent/fluentd-docs-gitbook/tree/f5f5f45fd170a81e4f34226d168621bcd4eb7e48/articles/docker-logging-efk-compose.md

**Comment by repeatedly** [comment]
Thanks! Just fixed.
