### ISSUE TITLE
Maximum size of output file

### ISSUE THREAD

**Issue by bhavsi** [fluent/fluentd-docs-gitbook#110]
I have been searching for a while now, but unable to find this information:

If I use out_file plugin in match section, what is the maximum file size that it can grow to (not the buffer, but the actual persistent output file), and what happens if it hits the limit?

**Comment by repeatedly** [comment]
No limit in out_file side. out_file only flushes the buffer to local file. So actual file size depends on buffer size.

**Comment by bhavsi** [comment]
Assuming buffer size is set to a reasonable value, and chunks are flushed periodically without issue, the out_file can grow as much as available disk space on the host machine? Does that mean if the out_file grows as much as possible (assuming no manual cleanup is done), there could be potential I/O issues on the host machine, or fluentd can crash and stop logging? 

If yes, then how do we mitigate that and rotate logs? 

PS: Using fluentd debian 1.7 docker image to read several containers' logs in source `forward` mode. Not using fluentd daemon process, so I can't use the command line "--log-rotate-age" and "--log-rotate-size" options.

**Comment by repeatedly** [comment]
> If yes, then how do we mitigate that and rotate logs?

Use other system instead of out_file. If you use out_file, you need to manage disk space and out_file result.

>  I can't use the command line "--log-rotate-age" and "--log-rotate-size" options.

This is for fluentd log, not out_file.

**Comment by bhavsi** [comment]
I am using a copy match plugin. I am shipping the logs to a destination, but I am required to also persist log files. Do you recommend I setup each container to log to default driver `json-file` and set `max-size` and `max-file` log-opts for each container, and then `in_tail` these docker container json log files? 
In that case (json-file logging driver), since I lose control to set tag for each container (which I could if I specified fluentd as logging driver), how can I tag each container log output by name? I have already setup parsing for each container based on tag (when I had each container's logging driver set as fluentd). Thanks!

**Comment by bhavsi** [comment]
@repeatedly Does this setting apply to out_file for container logs captured by fluentd? https://docs.fluentd.org/deployment/logging#log-rotation-setting? 
If so, how can it be used to configure in docker environment (not sure how to translate, for e.g. `--log-rotate-age 5` into docker/docker-compose commands). Thanks!

**Comment by repeatedly** [comment]
> Does this setting apply to out_file for container logs captured by fluentd?

See my previous comment.

> This is for fluentd log, not out_file.

**Comment by kenhys** [comment]
The answer of this issue seems to be resolved by https://github.com/fluent/fluentd-docs-gitbook/issues/110#issuecomment-546098405,  https://github.com/fluent/fluentd-docs-gitbook/issues/110#issuecomment-546113623 and https://github.com/fluent/fluentd-docs-gitbook/issues/110#issuecomment-546554527,
so I'll close this.

**Comment by kidlj** [comment]
https://docs.fluentd.org/deployment/logging

I think you should REALLY note that the `logging` configurations described in the page is for Fluentd itself, but not for logs that Fluentd collects.

As a newbie to Fluentd, I wasted hours testing the log rotation features described here, only to find here that the configurations are for Fluentd itself.
