### ISSUE TITLE
Wrong information about output frequency in "Send Apache Logs to S3" howto

### ISSUE THREAD

**Issue by lpugoy** [fluent/fluentd-docs-gitbook#112]
In the [page](https://docs.fluentd.org/how-to-guides/apache-to-s3), the following warning is displayed:
> WARNING: By default, files are created on an hourly basis (around xx:10). This means that when you first import records using the plugin, no file is created immediately. The file will be created when the time_slice_format condition has been met. To change the output frequency, please modify the time_slice_format value. To write files every minute, please use %Y%m%d%H%M for the time_slice_format.

The output frequency was not changed when `time_slice_format` was changed to `%Y%m%d%H%M`. However, changing the `timekey` parameter for the [buffer](https://docs.fluentd.org/configuration/buffer-section#time) worked.

**Comment by repeatedly** [comment]
Thanks!
Just updated
