### ISSUE TITLE
inter-branch link is broken

### ISSUE THREAD

**Issue by nokute78** [fluent/fluentd-docs-gitbook#114]
`v0.12 way` in
https://docs.fluentd.org/deployment/logging
is broken link.

It is the link from 1.0 branch to 0.12 branch.
How can we describe such links on gitbook?

**Comment by repeatedly** [comment]
Ah... the link should be https://docs.fluentd.org/v/0.12/deployment/logging

**Comment by repeatedly** [comment]
Finally fixed by https://github.com/fluent/fluentd-docs-gitbook/commit/ea39a7870ffa6c4a00a917d8c8ec8e3bd0a9b66a

**Comment by nokute78** [comment]
@repeatedly Thank you for quick fixing!
