### ISSUE TITLE
Incomplete documentation regarding service discovery and server plugin requirement

### ISSUE THREAD

**Issue by GypsyCosmonaut** [fluent/fluentd-docs-gitbook#133]
As mentioned in the documentation at
  [https://docs.fluentd.org/service_discovery](https://docs.fluentd.org/service_discovery)

I configured the output forward plugin with the same config, but when I start td-agent, I get the following error

`[error]: config error file="/etc/td-agent/td-agent.conf" error_class=Fluent::ConfigError error="forward output plugin requires at least one <server> is required"`

If I am required to add server helper in output forward plugin then what is the use of service discovery. This is contradicting. Either the documentation is wrong or the td-agent that I am working with is wrong. 

I am using td-agent version 1.7.4

**Comment by ganmacs** [comment]
your /etc/fluentd/sd.yaml possibly doesn't have any servers. see https://docs.fluentd.org/service_discovery/file

**Comment by GypsyCosmonaut** [comment]
Turns out the service discovery option was launched with Fluentd version v1.8.0 
Closing the issue as I was not testing with the correct version.
