### ISSUE TITLE
Which buffer type does out_http use?

### ISSUE THREAD

**Issue by bhavsi** [fluent/fluentd-docs-gitbook#135]
Does it use `file` or `memory` buffer type? We did a test deployment recently in which the `endpoint` was not configured to a legitimate URL. After about ~3 days the disk utilization by fluentd had shot up significantly resulting in issues in other docker containers deployed. 

My configuration is below:
```
<source>
  @type tail
  <parse>
    @type json
  </parse>
  path /var/lib/docker/containers/*/*-json.log
  pos_file /var/log/fluentd-docker.pos
  read_from_head true
  tag docker.*
  refresh_interval 5s
  enable_stat_watcher false
</source>

<filter docker.var.lib.docker.containers.**.*>
....
</filter>

<match docker.var.lib.docker.containers.**.*>
  @type rewrite_tag_filter
  <rule>
    ...
  </rule>
</match>

<match sometags>

  @type http
  endpoint DUMMY_URL
  open_timeout 120
  content_type application/json
  http_method post
  headers {"Authorization":"Bearer DUMMY_AUTHORIZATION_BEARER", "structure":"simple"}
  tls_verify_mode none
  <buffer>
    chunk_limit_records 300
    flush_interval 3s
    flush_at_shutdown true
    flush_thread_count 4
    overflow_action drop_oldest_chunk
    retry_max_times 4
  </buffer>

</match>
```

I have chosen the `overflow_action` as `drop_oldest_chunk`. The system storage is 32GB. According to the [buffer configuration section](https://docs.fluentd.org/configuration/buffer-section), `total_limit_size` is 512MB for `buf_memory` and 64GB for `buf_file`. Which leads me to believe that buffer type for `out_http` could be `buf_file`, since if it were memory, and 512MB is filled up, then the oldest chunk would be dropped. 

I am not able to find an accurate answer to this. I would appreciate help to confirm this. Thank you!

**Comment by repeatedly** [comment]
> Which buffer type does out_http use?

See article: https://docs.fluentd.org/configuration/buffer-section#buffer-plugin-type

> @type can be omitted. When @type parameter is not configured, the default buffer plugin specified by output plugin will be used (if possible), or memory buffer plugin in default.

So memory.

BTW, we don't use github issue for asking quesiton. Closed.
