### ISSUE TITLE
Fluentd homepage broken!

### ISSUE THREAD

**Issue by pranavmarla** [fluent/fluentd-docs-gitbook#149]
I was browsing the Fluentd documentation when, a few minutes back, something happened that broke the website.

Specifically:
1) As of now, the Fluentd homepage has lost all the sections to the left -- only 'Introduction' is available.
![fluentd-error-1](https://user-images.githubusercontent.com/6486632/74383020-66ac9c00-4dbc-11ea-9801-8b20b6da0007.PNG)

2) All URLs making use of those missing sections (eg. https://docs.fluentd.org/input/monitor_agent) either do not work (gives a 'Page Not Found' error) or only briefly go to the correct page before immediately redirecting to the homepage.
![fluentd-error-2](https://user-images.githubusercontent.com/6486632/74383032-6e6c4080-4dbc-11ea-9a1c-d9ef59867eac.PNG)

I have verified this on both Chrome and Opera. This seems to affect only the v1.0 documentation.

**Comment by repeatedly** [comment]
I confirmed it and this seems gitbook side issue.
I will contact gitbook soon.

**Comment by pranavmarla** [comment]
Thank you!

**Comment by repeatedly** [comment]
I got the response from gitbook team and their recent changes have parser related bug.
They are now trying to fix the problem.

**Comment by eredi93** [comment]
@repeatedly i made a PR to make it clearer where the docs source is https://github.com/fluent/fluentd-docs-gitbook/pull/150 
Yesterday i wasted a bit of time trying to find out where they were located

**Comment by repeatedly** [comment]
I got a workaround from gitbook developer and applied it.
The problem seems to be resolved on my environment.
Does anyone check the site?

**Comment by edsiper** [comment]
looks fine now :)

**Comment by pranavmarla** [comment]
Looks good, thanks!
