### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by hkz-aarvesen** [fluent/fluentd-docs-gitbook#152]
This section of documentation:

https://docs.fluentd.org/output#difference-between-v-1-0-and-v-0-12

Refers to the "Compat Parameters Plugin Helper API", which links to this missing page:

https://github.com/fluent/fluentd-docs-gitbook/tree/8c505a3608b9b2032813b00c9b5750f4ca29ddcd/plugin-helper-overview/api-plugin-helper-compat_parameters.md

It probably wants to link to this page:

https://docs.fluentd.org/plugin-helper-overview/api-plugin-helper-compat_parameters

**Comment by repeatedly** [comment]
#155 fixes this problem. Thanks for the report!
