### ISSUE TITLE
The "* Plugins" sections are missing from the 0.12 docs

### ISSUE THREAD

**Issue by syedriko** [fluent/fluentd-docs-gitbook#157]
There seem to be entire sections on plugins missing from the 0.12 documentation at https://docs.fluentd.org/v/0.12/. 

You can see an example of such disabled internal links in "We will use the in_http and the out_stdout plugins as examples" on the https://docs.fluentd.org/v/0.12/quickstart/life-of-a-fluentd-event page.

**Comment by repeatedly** [comment]
Thanks for the report.

This happens by recent gitbook summary parser changes. Just fixed!

**Comment by syedriko** [comment]
@repeatedly Cool, thanks! BTW, internal links on https://docs.fluentd.org/v/0.12/quickstart/life-of-a-fluentd-event still don't work.

**Comment by repeatedly** [comment]
The problem is gitbook's cache refers older SUMMARY.
I rebuild the article and broken links are fixed.
