### ISSUE TITLE
Parser plugins

### ISSUE THREAD

**Issue by alberttorosyan** [fluent/fluentd-docs-gitbook#158]
Incomplete documentation for parser plugins. 
    **List of Built-in Parsers** missing `@type msgpack`
    **List of Core Input Plugins with Parser support** missing `in_forward`

**Comment by repeatedly** [comment]
> List of Built-in Parsers missing @type msgpack

Thanks. Will add it.

> List of Core Input Plugins with Parser support missing in_forward

This is correct. `in_forward` doesn't support parser plugins.

**Comment by repeatedly** [comment]
Added msgpack article.
