### ISSUE TITLE
Install Docker fluentd conf file path not same across/confusing 

### ISSUE THREAD

**Issue by r-pai** [fluent/fluentd-docs-gitbook#161]
In the Install by docker doc page, in "Step2" section, the line "To make the test simple, create the example config below at /tmp/fluentd.conf" is contradicting/confusing with the next 'docker run command'. The line says to create the fluentd.conf in the root tmp folder but in the next line the docker run command expect the conf file to be present in the  $(pwd)/tmp folder. and thus fails when run.
"_docker run -p 9880:9880 -v $(pwd)/tmp:/fluentd/etc -e FLUENTD_CONF=fluentd.conf fluent/fluentd:v1.6-debian-1_" 

Doc path:
https://github.com/fluent/fluentd-docs-gitbook/blob/1.0/container-deployment/install-by-docker.md

**Comment by kenhys** [comment]
Thanks!

Fixed via #291
