### ISSUE TITLE
"Docker Logging" contains incorrect commands

### ISSUE THREAD

**Issue by johannes-riecken-dunnhumby** [fluent/fluentd-docs-gitbook#167]
The [guide on docker logging](https://www.fluentd.org/guides/recipes/docker-logging) needs to be updated, because many commands don't give the expected output. Problems I've found so far:

- The in_docker.conf contents of Step 1 don't match the contents shown in the logs of Step 2.
- Using the contents of Step 1 with the `docker run` command in Step 3 will give an error like
```
2020-04-06 18:47:33 +0200 [warn]: #0 no patterns matched tag="docker.{.ID}}"
2020-04-06 18:47:33.481204978 +0200 fluent.warn: {"tag":"docker.{.ID}}","message":"no patterns matched tag=\"docker.{.ID}}\""}
```
- The `docker run` command in Step 3 doesn't match the command shown in the image for Step 3.
- The `docker run` command should have a `--rm` flag to avoid polluting the container list with testing entries.
- When running the "Additional Step 1", the JSON key-value pair is not appended to the log line JSON object, but the output looks the same as if the JSON filter doesn't exist.

I've given up at that stage, because I'm new to Fluentd. The quality of the source code is very nice though :)

**Comment by kenhys** [comment]
Fixed via https://github.com/fluent/fluentd-website/pull/116.

Thanks!
