### ISSUE TITLE
label @FLUENT_LOG needs more description and examples

### ISSUE THREAD

**Issue by steveww** [fluent/fluentd-docs-gitbook#169]
It's not clear how to integrate <label @FLUENT_LOG> with other match commands.

For example I want K8s logs from my namespace and Fluentd to go to one elastic index.

Currently

```
<match {kubernetes.var.log.containers.**my-namespace**.log,fluent.**}>
@type elastcisearch
</match>
```

Should do it. What's the equivalent when using <label @FLUENT_LOG>??????

**Comment by kenhys** [comment]
It may be redundant, it will work if `@label @SOMETHING` is set.

```
<label @FLUENT_LOG>
  <match fluent.*>
     @type elasticsearch
     ...
  </match>
</label>

<label @SOMETHING>
  <match kubernetes.var.log.containers.**my-namespace**.log>
     @type elasticsearch
     ...
  </match>
<label>
