### ISSUE TITLE
fix match

### ISSUE THREAD

**Issue by phiran** [fluent/fluentd-docs-gitbook#175]
<match app.**> is depreciated. Should document new format
<label @myapp>
   <match app.**>

**Comment by repeatedly** [comment]
This issue is unclear. `<match app.**>` is not deprecated.

**Comment by phiran** [comment]
I was getting the following message in my td-agent.log
2020-05-11 11:20:07 -0400 [warn]: #0 define <match fluent.**> to capture fluentd logs in top level is deprecated. Use <label @FLUENT_LOG> instead

**Comment by repeatedly** [comment]
This is for only logging, not general `match`. See https://docs.fluentd.org/deployment/logging#deprecate-top-level-match

Closed.
