### ISSUE TITLE
json_parser can't parse time from nginx.json ($time_local)

### ISSUE THREAD

**Issue by ttsrg** [fluent/fluentd-docs-gitbook#177]
For example {"time": "14/May/2020:13:41:20 +0300",  but json_parses parses as `1970-01-01 03:33:40` UTC - **{
    "time": "1970-01-01 03:33:40 UTC",
    "remote": null,**

**Comment by repeatedly** [comment]
If you want to parse string time field, you need to specify time_format.
Check: https://docs.fluentd.org/parser/json#time_type

**Comment by ttsrg** [comment]
Specify time format, say it nginx.   
It helps me:
```
 <parse>
    @type json
    time_format %d/%b/%Y:%H:%M:%S %z
  </parse>
```
