### ISSUE TITLE
0.12 Plugin links cannot be accessed from 0.12 Overview page

### ISSUE THREAD

**Issue by ishigoya** [fluent/fluentd-docs-gitbook#178]
The links to the plugin pages in the body of [the v0.12 overview page](https://docs.fluentd.org/v/0.12/quickstart) cannot be clicked.

If this is a bug, I'd be happy to post a pull request.

**Comment by repeatedly** [comment]
Ah, I didn't notice it. If you can send a PR, we will review it :)

**Comment by ishigoya** [comment]
The links in `articles/quickstart.md` (the broken one) are the same as those in `overview/getting-started.md` (where the links work).

Is it possible that the file on Gitbook is an old version?

**Comment by kenhys** [comment]
Closed via #284
