### ISSUE TITLE
format deprecated

### ISSUE THREAD

**Issue by Julyne** [fluent/fluentd-docs-gitbook#179]
Hi there,

In this page, and other places, you specify that format is deprecated : https://docs.fluentd.org/input/http#format-deprecated

But you don't mention anything on this page : 
https://docs.fluentd.org/configuration/format-section

It's a little bit confusing as I'm trying to resolve a problem of format.... Is it possible to do something? Is it deprecated or not?

Thanks a lot

**Comment by iamAzeem** [comment]
@repeatedly 

The deprecation is specifically for those plugins only, wherever mentioned, e.g.  `in_http`.
It is not applicable in the general context.
So, this may safely be closed.

**Comment by kenhys** [comment]
Because of https://github.com/fluent/fluentd-docs-gitbook/issues/179#issuecomment-666901202, I'll close this issue.
