### ISSUE TITLE
docs.flunetd.org has no ip address

### ISSUE THREAD

**Issue by anvarich** [fluent/fluentd-docs-gitbook#181]
CNAME record also empty
 nslookup docs.fluentd.org 8.8.8.8 -v
Server:         8.8.8.8
Address:        8.8.8.8#53

** server can't find docs.fluentd.org: NXDOMAIN

**Comment by repeatedly** [comment]
I think this is the cause: https://twitter.com/GitBookStatus/status/1268448791126069248
We are now checking how to avoid the problem.

**Comment by repeatedly** [comment]
site is back :)
