### ISSUE TITLE
connection_string of out_mongo isn't documented

### ISSUE THREAD

**Issue by eagletmt** [fluent/fluentd-docs-gitbook#188]
README of fluent-plugin-mongo https://github.com/fluent/fluent-plugin-mongo#label-Configuration introduces `connection_string` parameter first, but gitbook https://docs.fluentd.org/output/mongo#parameters doesn't document it.

I think `connection_string` is more useful to use because it supports "mongodb+srv" scheme https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format .

**Comment by repeatedly** [comment]
Looks good > adding `connection_string`.
Could you send a patch?

**Comment by iamAzeem** [comment]
@repeatedly 

The type `:string` is missing for `connection_string`.

See: https://github.com/fluent/fluent-plugin-mongo/blob/769f0157e67d62eedb908995ed0d4c1fee3bea21/lib/fluent/plugin/out_mongo.rb#L23

**Comment by cosmo0920** [comment]
missing type information should be handled as `string` type.
See: https://github.com/fluent/fluentd/blob/d9533da0b41fc652c51d86bf773db6a0075d7973/lib/fluent/config/configure_proxy.rb#L230-L232

**Comment by cosmo0920** [comment]
#225 is merged. Closing.
