### ISSUE TITLE
Link is broken in stdout filter plugin

### ISSUE THREAD

**Issue by emamulandalib** [fluent/fluentd-docs-gitbook#194]
In the documentation of **stdout filter plugin** at the section `<inject>` I have found the link broken of the title **Inject section configurations**. I have provided the link below.

Link: [https://docs.fluentd.org/filter/stdout#less-than-inject-greater-than-section](https://docs.fluentd.org/filter/stdout#less-than-inject-greater-than-section)

**Comment by kenhys** [comment]
Fixed via #224
