### ISSUE TITLE
Fluentd Install By Gem documentation

### ISSUE THREAD

**Issue by padhidipika** [fluent/fluentd-docs-gitbook#217]
Reference page - https://docs.fluentd.org/installation/install-by-gem
Reference Section: Step 2 - Install Fluentd gem
![image](https://user-images.githubusercontent.com/19261536/88400068-1de91c80-ce0b-11ea-9202-c411e35c12e9.png)
gives: invalid option: --no-ri and invalid option: --no-rdoc

Following this page -
https://stackoverflow.com/questions/57475842/what-to-use-instead-of-no-ri-for-gem-install

I've installed fluentd as 
**gem install fluentd --no-document**

Please update the documentation accordingly

Thank You!

**Comment by cosmo0920** [comment]
#223 is merged. Closing.
