### ISSUE TITLE
Enviromnent Vaiable name is wrong when changing configration file name

### ISSUE THREAD

**Issue by Anorlondo448** [fluent/fluentd-docs-gitbook#218]
https://docs.fluentd.org/configuration/config-file#fluent_conf-environment-variable

> You can change the default configuration file location via FLUENT_CONF

x FLUENT_CONF
○ FLUENTD_CONF

It is FLUENTD_CONF in this code.
https://github.com/fluent/fluentd-docker-image/blob/master/entrypoint.sh.erb#L20

**Comment by repeatedly** [comment]
Hmm... above article is correct. 
This environment variable is for fluentd itself, not fluentd docker image.

https://github.com/fluent/fluentd/blob/be905c998382d4e9dacb49f510609fa3dc5ecfb8/lib/fluent/env.rb#L20

**Comment by Anorlondo448** [comment]
Thank you!
I make an issue towards the fluentd docker image
