### ISSUE TITLE
404 err in link "pluggable and customizable formats for input plugins. "

### ISSUE THREAD

**Issue by ttsrg** [fluent/fluentd-docs-gitbook#235]
https://docs.fluentd.org/plugin-development/api-plugin-parser

pluggable and customizable formats for input plugins. 
 https://github.com/fluent/fluentd-docs-gitbook/tree/701b465b45f0b6dcd8dd8937fe4649de7ca4e6ea/developer/parser-plugin-overview/README.md

**Comment by repeatedly** [comment]
Thanks for the report. Just fixed
