### ISSUE TITLE
Manuals has outdated plugin's version fluent-plugin-prometheus

### ISSUE THREAD

**Issue by ttsrg** [fluent/fluentd-docs-gitbook#236]
https://docs.fluentd.org/v/0.12/articles/monitoring-prometheus
$ sudo td-agent-gem install fluent-plugin-prometheus --version=0.4.0

```
td-agent-gem  search fluent-plugin-prometheus

*** REMOTE GEMS ***

fluent-plugin-prometheus (1.8.3)
```

May be more correct do not use option --version

**Comment by repeatedly** [comment]
Without `--version` option, it updates fluentd version to v1.
Above document is for v0.12, so need to specify `--version` option.
