### ISSUE TITLE
Fluent website docs missing most config options

### ISSUE THREAD

**Issue by RussellTaylor83** [fluent/fluentd-docs-gitbook#241]
I'm not sure if it's supposed to be a cut down list of configuration, but the page at

https://docs.fluentd.org/output/elasticsearch

Is missing most of the configuration options as far as I can tell. Is this by design? If so it may be worth making it clear that there is much more to be found at the Github repo.

Thanks for the plugin,

Russ

**Comment by repeatedly** [comment]
By design. So this article has `This document does not describe all the parameters. For details, refer to the Further Reading section.` line.

**Comment by RussellTaylor83** [comment]
It might be different to all the other pages, but that link would be more useful in the parameters section.
