### ISSUE TITLE
Windows Service logs don't rotate, no way to set rotation for the service

### ISSUE THREAD

**Issue by jrowlison-dart** [fluent/fluentd-docs-gitbook#246]
I've installed per the instructions for v4 [here](https://docs.fluentd.org/installation/install-by-msi) and as indicated the service was created. 

I failed initially to set the log level appropriately for the system logs, so they were filling up the folder on my VM. That's on me, and I've since adjusted it. The fact that the excessive logs filled the drive struck me as odd so I looked for log rotation options.

But when I visit the [system config](https://docs.fluentd.org/deployment/system-config) page and the [fluentd logging](https://docs.fluentd.org/deployment/logging) page I can't find instructions on how I could configure the windows service to rotate logs. Information about how to do this via command-line is provided, but the install guide and the automatic installation of the service suggest I should be able to use the agent via a service but if logs can't be set to rotate then I'm always at some risk of filling the drive.

Given the service is set up, I prefer to take advantage of it if I can, rather than trying to find another way of setting up the agent to start after machine restarts etc. But if it's just going to eventually fill the drive I'm not sure I have a choice.

Thanks in advance for any help.

**Comment by ashie** [comment]
Hmm, it seems that we should add documentation for it and default rotation setting to td-agent.

refs:
* https://github.com/fluent/fluentd/pull/2663
* https://github.com/fluent/fluentd/issues/2446

**Comment by kenhys** [comment]
FYI: https://github.com/fluent/fluentd/pull/3352 was merged.

The following notation will be supported in the future release.

```
<system>
  <log>
     rotate_age ...
     rotate_size ...
  <log>
</system>
```

**Comment by kenhys** [comment]
https://github.com/fluent/fluentd/pull/3352 will be released in the next release,
and documentation will be updated by https://github.com/fluent/fluentd-docs-gitbook/pull/316, so I'll close it.
