### ISSUE TITLE
Doc links in search results need redirects 

### ISSUE THREAD

**Issue by jordo1138** [fluent/fluentd-docs-gitbook#27]
Example: “fluentd output elasticsearch”
*Top result is*
https://docs.fluentd.org/v1.0/articles/out_elasticsearch

*Needs 301 redirect to*
https://docs.fluentd.org/output/elasticsearch
Google search console + cdn  is how I used to handle these redirects for often changing url promo changes at newegg.com, should be straight forward I think and help users 

just using google `site:docs.fluentd.org, inurl:articles`  theres 415 results under /articles indexed
here's first 136 using python I got before my ip was banned(forgot they have a pretty strict rate limit)
[results.txt](https://github.com/fluent/fluentd-docs-gitbook/files/3205763/results.txt)
I see you already do a redirect in your .gitbook.yaml for https://docs.fluentd.org/v1.0/articles/quickstart
so maybe can just be handled there if you don't want to mess with seo way of redirects, eventually google crawlers will learn the structure anyhow.

**Comment by fujimotos** [comment]
@jordo1138 Thanks for reporting the issue, Jordan.

We acknowledge the issue & will fix that soon. Our plan right now
is to add more redirections to .gitbook.yaml just as you did in #29.
So please wait a bit.

**Comment by y-ken** [comment]
There are many type of url are vanished. Is this helps you to know the pattern?
https://github.com/y-ken/fluent-plugin-geoip/pull/83/files

Are there any way to collect 404 not found page list with using javascript in gitbook?

**Comment by jordo1138** [comment]
@y-ken the analytics.js used on this gitbook site can give you 404 report in GA, would be a start beyond what I mentioned around uri with v1.0 etc in path

**Comment by y-ken** [comment]
@jordo1138 Thanks! I have shared url patterns for @fujimotos with using access log.
It can be cover previous known url. After that, it would be better to track 404 report in GA, too.

**Comment by fujimotos** [comment]
So I added redirection mappings for all the v1.0 articles.
Here is an example:

```
$ curl -I https:/docs.fluentd.org/v1.0/articles/graylog2
HTTP/2 302 
location: /how-to-guides/graylog2
...
```

I also checked the access log provided by @y-ken and confirmed that
accesses to the `/v1.0/` articles are redirected properly.

**Comment by repeatedly** [comment]
@fujimotos Thanks for awesome work!

**Comment by fujimotos** [comment]
Thank you. I close this ticket now.

**Comment by jordo1138** [comment]
@fujimotos nice, looks good for v1.0, assuming you'll do the same for v0.12 doc links then?
