### ISSUE TITLE
Better documentation for nested attributes.

### ISSUE THREAD

**Issue by andrew-pickin-epi** [fluent/fluentd-docs-gitbook#273]
This page https://docs.fluentd.org/v/0.12/output/rewrite_tag_filter

should include an example of nested-attributes as per
https://github.com/fluent/fluent-plugin-rewrite-tag-filter#nested-attributes

This is a common pattern especially when using kubernetes and should be a little easier to find.

**Comment by kenhys** [comment]
Close #281 was merged.
(v0.12 ends support lifecycle so updated 1.0 document only)
