### ISSUE TITLE
On faq page Link to buf_file article is broken

### ISSUE THREAD

**Issue by MNF** [fluent/fluentd-docs-gitbook#274]
On page https://docs.fluentd.org/v/0.12/quickstart/faq
Link to buf_file article https://github.com/fluent/fluentd-docs-gitbook/tree/507e377b7e8e78a312dc49e76bd9a302c33fd058/overview/buf_file/README.md#limitation is broken

**Comment by kenhys** [comment]
@MNF 

Thanks, fixed via https://github.com/fluent/fluentd-docs-gitbook/pull/282
