### ISSUE TITLE
Broken link in v1 config file syntax page

### ISSUE THREAD

**Issue by ishigoya** [fluent/fluentd-docs-gitbook#287]
The link in [this page](https://docs.fluentd.org/configuration/config-file) is to

https://docs.fluentd.org/configuration/config-file#how-match-patterns-work

but the actual destination is

https://docs.fluentd.org/configuration/config-file#how-do-the-match-patterns-work

**Comment by ishigoya** [comment]
PR is [here](https://github.com/fluent/fluentd-docs-gitbook/pull/288)

**Comment by ashie** [comment]
#288 has been merged.
Thanks!
