### ISSUE TITLE
fluent-logger-php prerequisites possibly wrong

### ISSUE THREAD

**Issue by xhnilic3** [fluent/fluentd-docs-gitbook#293]
I noticed that requirements of minamal version of PHP between your [documentation](https://docs.fluentd.org/language-bindings/php):
![image](https://user-images.githubusercontent.com/15017154/111823134-df95f580-88e4-11eb-9cd1-fd0f4322eee1.png)

 and fluent logger README.md on [github](https://github.com/fluent/fluent-logger-php#requirements):

![image](https://user-images.githubusercontent.com/15017154/111823195-f1779880-88e4-11eb-9f7c-d1a18584ed17.png)

 is slightly inconsistent. As you can see, you declare 5.3 or higher in one case (documentation mentioned above). On the other hand, on github we can see 5.6 or higher. I would like to ask you, which information is up to date. Thank you so much.

Best regards.
JH

EDIT: incorrect url

**Comment by kenhys** [comment]
It may be https://docs.fluentd.org/language-bindings/php is outdated.

**Comment by kenhys** [comment]
It should be fixed by https://github.com/fluent/fluentd-docs-gitbook/pull/301

**Comment by ashie** [comment]
#301 has been merged. Thanks!
