### ISSUE TITLE
Docker Compose example uses invalid parameters for elasticsearch

### ISSUE THREAD

**Issue by chainhead** [fluent/fluentd-docs-gitbook#294]
The following keys do not exist in the [documentation](https://docs.fluentd.org/output/elasticsearch#parameters) of `elasticsearch` output plugin. Whereas, they are referred to in the [Docker Compose example](https://docs.fluentd.org/container-deployment/docker-compose) 

- `include_tag_key`
- `type_name`
- `tag_key`

**Comment by kenhys** [comment]
Thanks!

According to https://docs.fluentd.org/output/elasticsearch#parameters 

> This document does not describe all the parameters. For details, refer to the Further Reading section.

So, there is a case that undocumented parameter is used. but it is not user-friendly.
It may be better to add a missing guide to the undocumented parameter.

**Comment by ashie** [comment]
Fixed by #294
