### ISSUE TITLE
roundrobin output plugin example references tcp output plugin, which does not exist in core fluentd

### ISSUE THREAD

**Issue by LorenKeagle** [fluent/fluentd-docs-gitbook#325]
I spent a long time trying to figure out how to send my events over a raw TCP socket.  Fluentd core has a raw TCP input plugin, but no raw TCP output plugin that I can find. 

However, the documentation for this roundrobin output plugin suggests that core fluentd has a tcp output plugin that can be used.  Since this is not the case, I recommend changing the example to use a core output plugin.

Or better yet, include a TCP output plugin in the core implementation :-)

**Comment by kenhys** [comment]
> I recommend changing the example to use a core output plugin.

It is a good suggestion not to make new user confused.

**Comment by kenhys** [comment]
It should be fixed by https://github.com/fluent/fluentd-docs-gitbook/pull/329

**Comment by kenhys** [comment]
#329 was merged :+1:
