### ISSUE TITLE
Explain reserve_time

### ISSUE THREAD

**Issue by Guillaume-Mayer** [fluent/fluentd-docs-gitbook#334]
I have a hard time understanding the **reserve_time** option of the parser filter.
If I enable or disable the option, I cannot see any difference.
Also it seems slightly different of **keep_time_key** but not sure how.

The documentation is very succinct and show no examples.
If this could be improved it would be nice.

Thanks

**Comment by kenhys** [comment]
I hope that it will help https://github.com/fluent/fluentd-docs-gitbook/pull/335

**Comment by kenhys** [comment]
#335 wes merged.

**Comment by Guillaume-Mayer** [comment]
That's perfectly explained! Thanks!
