### ISSUE TITLE
Config Advisor link is dead

### ISSUE THREAD

**Issue by kishorbhat** [fluent/fluentd-docs-gitbook#340]
The config advisor link under [config-file#config-advisor](https://docs.fluentd.org/configuration/config-file#config-advisor) seems to be dead.

**Comment by kenhys** [comment]
Hmm, http://fluentd-config-analyzer.calyptia.com/ might be discontinued.
It may be migrated to https://cloud.calyptia.com/#/visualizer  (login required)

**Comment by cosmo0920** [comment]
Yes. We recommend to use https://cloud.calyptia.com/#/visualizer instead.

**Comment by agup006** [comment]
Thank you for reporting @kishorbhat , fixed the link to our visualizer.

**Comment by cosmo0920** [comment]
We changed the descriptions for config advisor:
https://github.com/fluent/fluentd-docs-gitbook/commit/559b82def0c10d6fdd3f9039a6c9223bbfbb5ac2#diff-4dc58df3e8c2c7f01143f3966fd29914346f12e81958a099dec7a097f46ece28
Closing.
