### ISSUE TITLE
filter/grep multiple <and> in one filter

### ISSUE THREAD

**Issue by vogtph** [fluent/fluentd-docs-gitbook#343]
Fluentd complains about the filter below about using key verb pattern /get/ 2 times. It works if 2 filters are used.

      <filter tail.file.**>
        @type grep
        <and>
          <exclude>
             key verb
             pattern /get/
          </exclude>

          <exclude>
             key $.objectRef.resource
             pattern /namespaces/
          </exclude>
        </and>

        <and>
          <exclude>
             key verb
             pattern /get/
          </exclude>

          <exclude>
             key $.objectRef.resource
             pattern /clusterrolebindings/
          </exclude>
         </and>
      </filter>

**Comment by kenhys** [comment]
> Fluentd complains about the filter below about using key verb pattern /get/ 2 times. It works if 2 filters are used.

It seems natural because `key verb` and `key $.objectRef.resource` is duplicated apparently.
