### ISSUE TITLE
Description of Elasticsearch and Kibana are incorrect

### ISSUE THREAD

**Issue by stockholmux** [fluent/fluentd-docs-gitbook#348]
### Describe the bug

The docs describe Elasticsearch and Kibana as open-source. 

_Elasticsearch is an open-source search engine known for its ease of use. Kibana is an open-source Web UI that makes Elasticsearch user-friendly for marketers, engineers and data scientists alike._

[This is no longer correct as per Elastic](https://www.elastic.co/pricing/faq/licensing#does-this-mean-that-elasticsearch-and-kibana-are-no-longer-open-source) and the versions linked in the documentation are also not open source (7.13).

### Link to the problematic documentation

https://docs.fluentd.org/container-deployment/docker-compose

### Expected explanation

Either correctly describe Elasticsearch & Kibana as non-open source or consider alternative software that is open source.

**Comment by kenhys** [comment]
Fixed by #349
