### ISSUE TITLE
Documentation calls a backward slash a forward slash

### ISSUE THREAD

**Issue by gmcelhoe** [fluent/fluentd-docs-gitbook#360]
### Describe the bug

The text of the section on escaping characters in config files shows the glyph of a backward slash, but the text erroneously names it a forward slash.

### Link to the problematic documentation

https://docs.fluentd.org/configuration/config-file#in-double-quoted-string-literal-is-the-escape-character

### Expected explanation

The character \  should be referred to as a backward slash.

**Comment by kenhys** [comment]
@gmcelhoe could you send PR, please?

**Comment by kenhys** [comment]
Fixed by #364
