### ISSUE TITLE
Can't launch demon for installation by DEB package when using Debian Docker image (Bullseye)

### ISSUE THREAD

**Issue by junghanKang** [fluent/fluentd-docs-gitbook#366]
### Describe the bug

I used to use `php:7.1.12-apache-jessie` docker image and installed fluentd with 
`# td-agent 3
curl -L https://toolbelt.treasuredata.com/sh/install-debian-jessie-td-agent3.sh | sh` 
and was able to use `/etc/init.d/td-agent` script.

However, when I upgrade the image to `php:7.3-apache` which is Debian Bullseye, 
`# td-agent 4
curl -L https://toolbelt.treasuredata.com/sh/install-debian-buster-td-agent4.sh | sh`
can't generate `/etc/init.d/td-agent` script.

When I did several trials, I found just running `td-agent` which seems running `/usr/sbin/td-agent` starts fluentd without issues. 

Could you check this difference for Deamon launch?
Thank you.

### Link to the problematic documentation

https://docs.fluentd.org/installation/install-by-deb#init-d

### Expected explanation

I'd like to get confirmation my alternative way to initiate fluentd on docker container is appropriate.

**Comment by repeatedly** [comment]
Newer debian uses systemd and td-agent 4 also uses it on systemd based distribution.

https://docs.fluentd.org/installation/install-by-deb#systemd

**Comment by junghanKang** [comment]
> Newer debian uses systemd and td-agent 4 also uses it on systemd based distribution.
> 
> https://docs.fluentd.org/installation/install-by-deb#systemd

Ok, that's why init.d doesn't work with new debian. 
But unfortunately, it seems hard to use systemd in docker container. 
```
root@b168b0d775be:# systemctl status td-agent.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
root@b168b0d775be:# sudo systemctl status td-agent.service
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down 
```

then, for now, I guess I need to use `/usr/sbin/td-agent`

Thank you for the reply.
