### ISSUE TITLE
Conflicting information about json formatter defaults

### ISSUE THREAD

**Issue by virullius** [fluent/fluentd-docs-gitbook#381]
### Describe the bug

The [How To Use](https://docs.fluentd.org/formatter#how-to-use) section of the Formatter Plugins page states "each line is a single JSON object with "time" and "tag fields to retain the event's timestamp and tag". However, the [json](https://docs.fluentd.org/formatter/json) formatter page states "By default, json formatter result doesn't contain tag and time fields." and gives no indication how to configure it to include the time and tag fields.

Taking a look at [formatter_json.rb](https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/formatter_json.rb), there does not appear a way to include the time and tag field in any configuration.

### Link to the problematic documentation

https://docs.fluentd.org/formatter#how-to-use

### Expected explanation

Change the Formatter documentation to reflect the actual functionality.

**Comment by kenhys** [comment]
@virullius 
Thank you for your feedback, it seems that "How to use" explanation isn't accurate.

**Comment by kenhys** [comment]
Fixed via #383
