### ISSUE TITLE
Enable Google Analytics 4 (GA4) for docs.fluentd.org

### ISSUE THREAD

**Issue by chalin** [fluent/fluentd-docs-gitbook#437]
For context, see:

- https://github.com/fluent/fluentd-website/issues/243

Inspecting the dynamically generated pages, it seems that the following UA ID is being used `UA-181341719-4`.

/cc @caniszczyk @nate-double-u

**Comment by chalin** [comment]
@ashie @fujimotos - quoting https://www.gitbook.com/integrations/googleanalytics:

> GitBook admins can enable the Google Analytics integration by navigating to organization settings.

Can you setup GA to use the new GA4 ID `G-93T2VC0VBC`? If not, who can?

Note that I see this asset file for analytics: https://github.com/fluent/fluentd-docs-gitbook/blob/1.0/.gitbook/assets/js/googleanalytics.js, but I don't think that that is actually being used. If it isn't used, then it should probably be removed.

**Comment by chalin** [comment]
cc @toru-takahashi, please see the previous comment.

**Comment by toru-takahashi** [comment]
Let me check it in this week.

**Comment by chalin** [comment]
Thank you @toru-takahashi.

**Comment by chalin** [comment]
@toru-takahashi - any updates?

**Comment by chalin** [comment]
Thanks again for getting back to me @toru-takahashi. My currently unresolved questions are stated here: https://github.com/fluent/fluentd-docs-gitbook/issues/437#issuecomment-1317946965.

Are you a GitBook admin? If not, who is. If so, can you enable the GA4 ID `G-93T2VC0VBC`? Thank you.

**Comment by chalin** [comment]
Friendly ping. Any update on this?

**Comment by toru-takahashi** [comment]
@chalin 
Sorry, I missed this thread.
I'm not Gitbook Admin. fluentd gitbook may be managed by @ashie? Let me check

**Comment by chalin** [comment]
Thank you. Looking forward to hearing back from you.

**Comment by toru-takahashi** [comment]
I've checked with Ashie, but they don't manage Gitbook.
I guess it is also managed by @edsiper - Calyptia team.
Can u check it?

**Comment by chalin** [comment]
I communicated with @edsiper via the CNCF Slack, thanks.

**Comment by erikbledsoe** [comment]
@chalin I just tried adding a second Google tag into the GitBook GA plugin and it seems not to work—it stopped sending any data. I couldn't find any documentation to suggest that it would (or wouldn't), but I thought I'd try. 

Perhaps we could [combine the two tags](https://support.google.com/google-ads/answer/12329709?hl=en-AU)? I've never tried that; do you have experience with it?

**Comment by edsiper** [comment]
I did some changes in gitbook, pls confirm if is ok now:

<img width="1155" alt="image" src="https://github.com/fluent/fluentd-docs-gitbook/assets/369718/fa9236df-9547-4941-bbad-64ef1822b9dd">

**Comment by chalin** [comment]
Yes, the GA4 site tag is receiving events, thanks!

> <img width="861" alt="image" src="https://github.com/fluent/fluentd-docs-gitbook/assets/4140793/b95467aa-7380-4597-a65f-b6a40a112c07">
