### ISSUE TITLE
Better name for the "Monitoring Prometheus" page

### ISSUE THREAD

**Issue by ghost** [fluent/fluentd-docs-gitbook#450]
### Describe the bug

The name "Monitoring Prometheus" in https://docs.fluentd.org/v/0.12/articles/monitoring-prometheus makes it sound like it's about using Fluentd to monitor Prometheus.

It would be more descriptive if this page was renamed to something like "Monitoring with Prometheus"

### Link to the problematic documentation

https://docs.fluentd.org/v/0.12/articles/monitoring-prometheus

### Expected explanation

Rename to "Monitoring with Prometheus"

**Comment by daipom** [comment]
Thanks for reporting. I made the PR.

**Comment by daipom** [comment]
Merged!
