### ISSUE TITLE
Mismatch of '@label' argument in "Config: Common Parameters" page

### ISSUE THREAD

**Issue by UhyeongJo** [fluent/fluentd-docs-gitbook#454]
### Describe the bug

Hello, I found one mismatch argument in the example of the config file for `@label`.

The value of the parameter `@label` in the `<source>` section is `@access_logs`. 
But the argument of `<label>` section is '@access_log'.

So I think we should change `<label @access_log>` to `<label @access_logs>`.

Thank you.

### Link to the problematic documentation

https://docs.fluentd.org/configuration/plugin-common-parameters#label

### Expected explanation

Modify to `<label @access_logs>`.

**Comment by daipom** [comment]
Thanks!
