### ISSUE TITLE
Windows server 2019 docker image - fluentd.bat -v command 

### ISSUE THREAD

**Issue by psandeep09** [fluent/fluentd-docs-gitbook#473]
### Describe the bug

![image](https://github.com/fluent/fluentd-docs-gitbook/assets/51378608/4ff0afdb-a377-46f9-9abf-847cd4a07ab4)

### Link to the problematic documentation

https://docs.fluentd.org/deployment/logging

### Expected explanation

The -v option sets the verbosity to debug while the -vv option sets the verbosity to trace.

**Comment by psandeep09** [comment]
It's working with - .\fluentd.bat -v --config "C:\opt\td-agent\etc\td-agent\td-agent.conf"

**Comment by daipom** [comment]
This is expected.

You need the config file to run Fluentd.
As documented here, the path is `/etc/fluent/fluent.conf` (`C:\etc\fluent\fluent.conf`) by default.

* https://docs.fluentd.org/deployment/command-line-option

As you say, if the path is different from the default value, you need to specify it.

> It's working with - .\fluentd.bat -v --config "C:\opt\td-agent\etc\td-agent\td-agent.conf"
