### ISSUE TITLE
calyptia-fluentd: Installation for MacOs need information

### ISSUE THREAD

**Issue by mohantangirala** [fluent/fluentd-docs-gitbook#496]
### Describe the bug

The installation instruction needs a pre-requisite for MacOs - Sonoma, which is upgrade or have another ruby version with is 3.0 or above with out with Mac Os is taking the OOTB version 2.6.x causing no response in the fluentd process 

### Link to the problematic documentation

https://docs.fluentd.org/installation/install-by-dmg

### Expected explanation

Pre-requisite 
1. Install ruby version 3.x using brew and update the path variable.
2. https://mac.install.guide/ruby/update

**Comment by neut0ne** [comment]
Added a fix in pr #500: https://github.com/fluent/fluentd-docs-gitbook/pull/500/files

**Comment by daipom** [comment]
> The installation instruction needs a pre-requisite for MacOs - Sonoma, which is upgrade or have another ruby version with is 3.0 or above with out with Mac Os is taking the OOTB version 2.6.x causing no response in the fluentd process

Is this about calyptia-fluentd?

**Comment by mohantangirala** [comment]
Yes, this is about calyptia-fluentd

**Comment by daipom** [comment]
Hmm, sorry, I don't know much about calyptia-fluentd.
Is Ruby not included in that package?

**Comment by mohantangirala** [comment]
No it is not.

**Comment by daipom** [comment]
@cosmo0920 
Could you please review this and #500?
