### ISSUE TITLE
Remove incorrect gem install options

### ISSUE THREAD

**Issue by kennedyalexander** [fluent/fluentd-docs-gitbook#54]
Gem install options --no-ri and --no-rdoc are out of date. 
Replace them with --no-document.
Gem documentation: https://gitlab.com/gitlab-org/gitlab-ce/issues/55740
Page that needs updating: https://docs.fluentd.org/installation/install-by-gem

**Comment by ganmacs** [comment]
I confirmed the oldest ruby version we support is 2.1.0. And also ruby 2.1.0's the version of RubyGems is 2.2.0.
Considering the [history page](https://github.com/rubygems/rubygems/blob/571a6a7ab56c495bafeeb55df46908ac5d74ab42/History.txt#L2185), this proposal seems reasonable.

Could you send us a patch?

**Comment by digikin** [comment]
I submitted an issue with corrections.

**Comment by kenhys** [comment]
Fixed via #217
