### ISSUE TITLE
On "Free Alternative To Splunk", the Fluentd Architecture link is broken

### ISSUE THREAD

**Issue by G-Harmon** [fluent/fluentd-docs-gitbook#56]
page: https://docs.fluentd.org/how-to-guides/free-alternative-to-splunk-by-fluentd
At the bottom in the Learn More Section, the link to "fluentd architecture" points to https://github.com/fluent/fluentd-docs-gitbook/tree/159b4cb7cc0f9e0d33d3a3abbc13754c2c8ee64d/www.fluentd.org/architecture/README.md which is not found.

Maybe it means to point to https://www.fluentd.org/architecture ?

**Comment by ganmacs** [comment]
Thank you for your report! Yes. you are right. 
Could you send us a patch if you have time?

**Comment by kenhys** [comment]
It seems that this issue was already fixed.
