### ISSUE TITLE
Default value for the time_type option

### ISSUE THREAD

**Issue by shou10152208** [fluent/fluentd-docs-gitbook#60]
Default value of time_type option may be correct `string` .

page: https://docs.fluentd.org/configuration/parse-section#time-parameters
Default: `float`

https://github.com/fluent/fluentd/blob/a0240f6b7d897502fa36f9a720f9fb6b85a23bae/lib/fluent/time.rb#L142
Default: `string`

thx

**Comment by ganmacs** [comment]
Thank you for your report! Could you send us a patch if you have time?

**Comment by shou10152208** [comment]
OK! I sent a patch #62

**Comment by shou10152208** [comment]
Thank you. I closed this ticket.
