### ISSUE TITLE
On "Install by RPM Package (Redhat Linux)" , The differences between Fluentd and td-agent  link is gone

### ISSUE THREAD

**Issue by know-no** [fluent/fluentd-docs-gitbook#65]
In page https://docs.fluentd.org/installation/install-by-rpm,  the link for " differences between Fluentd and td-agent can be found here."  is gone.

That's why Treasure Data, Inc is providing the stable distribution of Fluentd, called td-agent. The differences between Fluentd and td-agent can be found **here**.

**Comment by ganmacs** [comment]
Thank you for the report! #55 should fix these issues.
