### ISSUE TITLE
Typo in Year in the regexp parser plugin example in v1.0

### ISSUE THREAD

**Issue by harshshekhar15** [fluent/fluentd-docs-gitbook#78]
Screenshot of the typo: 
![image](https://user-images.githubusercontent.com/40303207/61442251-e082c100-a964-11e9-89e2-f9924d4191af.png)
Link to the doc : https://docs.fluentd.org/parser/regexp

**Comment by ganmacs** [comment]
Thank you for the report. #79 should fix this issue.

https://docs.fluentd.org/parser/regexp#example

**Comment by harshshekhar15** [comment]
Hi @ganmacs, just noticed the same typo is present in v0.12 too.
Link to the doc: https://docs.fluentd.org/v/0.12/parser/regexp

**Comment by ganmacs** [comment]
I missed that. thank you https://github.com/fluent/fluentd-docs-gitbook/pull/81
